[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0057A8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f7ff"
textColor = "#1e293b"
font = "sans serif"
